services:
  wordpress-cli:
    image: wordpress:cli
    tty: true
    stdin_open: true
    depends_on:
      wordpress:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}:${DB_PORT}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD_FILE: ${DB_PASSWORD_FILE}
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_REDIS_HOST', '${REDIS_HOST}' );
        define( 'WP_REDIS_PORT', ${REDIS_PORT} );
      WORDPRESS_LOCALE: ${WORDPRESS_LOCALE}
      WORDPRESS_URL: ${WORDPRESS_URL}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
    secrets:
      - db_password
    tmpfs:
      - /var/cache/nginx:size=512M,mode=0755
    volumes:
      - wordpress:/var/www/html
      - ./scripts:/scripts:ro
    networks:
      - app-network
      - isolated
    command: /bin/sh /scripts/setup-wordpress.sh
