include:
  - mariadb.yaml
  - redis.yaml
  - nginx.yaml
services:
  wordpress:
    image: wordpress:php8.5-fpm-alpine
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_REDIS_HOST', 'redis' );
        define( 'WP_REDIS_PORT', 6379 );
    secrets:
      - db_password
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network
      - isolated

networks:
  app-network:
    driver: bridge
  isolated:
    internal: true

secrets:
   db_root_password:
     file: db_root_password.txt
   db_password:
     file: db_password.txt

volumes:
  wordpress:
  mariadb:
  redis:
